import { useEffect, useMemo, useState } from "react";
import { io } from "socket.io-client";
import "./App.css";

const socket = io("http://localhost:3001");
type GameStatus="LOBBY"|"BRIEFING"|"INVESTIGATION"|"FINALE";type PlayerRole="INSIDER"|"ANALYST";type LocationId="HQ"|"VELVET"|"HOTEL";
interface Player{id:string;name:string;host:boolean;role:PlayerRole;ready:boolean}
interface GameRoom{code:string;players:Player[];status:GameStatus;chapter:number;solved:boolean;attempts:number;notes:string[];clues:string[];unlockedLocations:LocationId[]}
interface CaseData{role:PlayerRole;people:{name:string;detail:string}[]|null;witness:string[]|null;plate:string|null;registry:{plate:string;owner:string;person:string}[]|null;cctvSecond:number}

function Cctv({data,onClue}:{data:CaseData;onClue:(c:string)=>void}){
 const [playing,setPlaying]=useState(false),[t,setT]=useState(0);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setT(v=>{const n=+(v+.1).toFixed(1);if(n>=12){setPlaying(false);return 12}return n}),100);return()=>clearInterval(id)},[playing]);
 const car=t>data.cctvSecond-1.2&&t<data.cctvSecond+1.8;
 const plateVisible=car&&Math.abs(t-data.cctvSecond)<.65;
 const stamp=`00:30:${String(48+Math.floor(t)).padStart(2,"0")}`;
 return <section className="cctv"><div className="cctv-head"><span>CAM 04 // HINTERHOF</span><b>{stamp}</b></div><div className="cctv-screen"><img src="/velvet-backyard.svg"/><div className="scanlines"/>{car&&<div className="moving-car"><div className="car-body"/><div className={plateVisible?"plate flash":"plate"}>{plateVisible?(data.plate||"??-?? ???"):"██████"}</div></div>}<div className="rec">● REC</div></div><div className="timeline"><div className="bar"><i style={{width:`${t/12*100}%`}}/></div><span>{t.toFixed(1)} / 12.0 s</span></div><div className="controls"><button onClick={()=>setPlaying(v=>!v)}>{playing?"PAUSE":"PLAY"}</button><button onClick={()=>{setPlaying(false);setT(0)}}>ZURÜCK</button><button onClick={()=>onClue("CCTV-Sequenz CAM 04 untersucht")}>ALS UNTERSUCHT MARKIEREN</button></div><p className="tip">Tipp: In der Aufnahme ist etwas nur sehr kurz lesbar. Pausieren kann sich lohnen.</p></section>
}

export default function App(){
 const [connected,setConnected]=useState(socket.connected),[playerName,setPlayerName]=useState(""),[joinCode,setJoinCode]=useState(""),[room,setRoom]=useState<GameRoom|null>(null),[error,setError]=useState(""),[answer,setAnswer]=useState(""),[result,setResult]=useState(""),[caseData,setCaseData]=useState<CaseData|null>(null),[location,setLocation]=useState<LocationId>("HQ"),[tab,setTab]=useState("scene"),[note,setNote]=useState("");
 useEffect(()=>{const on=()=>setConnected(true),off=()=>setConnected(false),ru=(r:GameRoom)=>{setRoom(r);setError("")};socket.on("connect",on);socket.on("disconnect",off);["room:created","room:updated","game:started","chapter:started"].forEach(e=>socket.on(e,ru));socket.on("room:error",setError);socket.on("case:data",setCaseData);socket.on("chapter:result",(d:{correct:boolean;room:GameRoom;message:string})=>{setRoom(d.room);setResult(d.message)});return()=>{socket.off("connect",on);socket.off("disconnect",off);["room:created","room:updated","game:started","chapter:started"].forEach(e=>socket.off(e,ru));socket.off("room:error");socket.off("case:data");socket.off("chapter:result")}},[]);
 const me=room?.players.find(p=>p.id===socket.id);
 useEffect(()=>{if(room?.status==="INVESTIGATION"&&!caseData)socket.emit("case:request",room.code)},[room?.status,room?.code,caseData]);
 const addNote=()=>{if(!room||!note.trim())return;socket.emit("notebook:add",{code:room.code,note});setNote("")};
 const clue=(c:string)=>room&&socket.emit("clue:found",{code:room.code,clue:c});
 const create=()=>socket.emit("room:create",playerName),join=()=>socket.emit("room:join",{code:joinCode,playerName}),start=()=>room&&socket.emit("game:start",room.code),ready=()=>room&&socket.emit("briefing:ready",room.code),submit=()=>room&&socket.emit("chapter:answer",{code:room.code,answer});
 const unlocked=useMemo(()=>new Set(room?.unlockedLocations||[]),[room?.unlockedLocations]);

 if(room?.status==="INVESTIGATION"&&me&&caseData)return <main className="game"><div className="rain"/><header className="topbar"><div><span className="eyebrow">NIGHTSHIFT // FALL 001</span><h1>DIE VERSCHWUNDENE</h1></div><div className="topmeta"><span>02:24</span><span>{me.role}</span><span className="online-pill">● PARTNER ONLINE</span></div></header><div className="game-layout"><nav className="locations"><h3>ORTE</h3><button className={location==="HQ"?"active":""} onClick={()=>setLocation("HQ")}>⌂ ERMITTLUNGS-HQ</button><button className={location==="VELVET"?"active":""} onClick={()=>setLocation("VELVET")}>◆ VELVET</button><button disabled={!unlocked.has("HOTEL")} className={location==="HOTEL"?"active":""} onClick={()=>setLocation("HOTEL")}>▣ HOTEL {unlocked.has("HOTEL")?"":"// GESPERRT"}</button><div className="case-progress"><span>GEFUNDENE SPUREN</span><b>{room.clues.length}</b><span>VERSUCHE</span><b>{room.attempts}</b></div></nav><section className="workspace">
 {location==="HQ"&&<><div className="location-title"><span>ERMITTLUNGS-HQ</span><h2>FALLAKTE & NOTIZBUCH</h2></div><div className="hq-grid"><article className="board"><h3>AKTUELLER AUFTRAG</h3><p>Rekonstruiert Vanessas letzte Stunde im VELVET. Findet eine belastbare Verbindung zwischen der Person im Hinterhof und einem bekannten Kontakt.</p><div className="objective">ZIEL // IDENTIFIZIERT DIE VERBINDUNG DES FAHRZEUGS</div>{room.solved&&<div className="success-box"><b>SPUR BESTÄTIGT</b><p>Eine neue Adresse wurde freigeschaltet. Besucht das Hotel.</p></div>}</article><article className="notebook"><h3>GEMEINSAMES NOTIZBUCH</h3><div className="notes">{room.notes.length?room.notes.map((n,i)=><div key={i}>#{String(i+1).padStart(2,"0")} {n}</div>):<p>Noch keine Notizen. Schreibt euch Kennzeichen, Uhrzeiten, Namen und Widersprüche auf.</p>}</div><div className="note-add"><input value={note} onChange={e=>setNote(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addNote()} placeholder="Beobachtung notieren…"/><button onClick={addNote}>+ NOTIZ</button></div></article></div><section className="solve-box"><h3>SPUR PRÜFEN</h3><p>Wenn ihr glaubt, die Person hinter der Fahrzeugspur identifiziert zu haben, gebt den Namen ein.</p><div className="answer-row"><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Name…"/><button className="primary" onClick={submit}>ÜBERPRÜFEN</button></div>{result&&<p className={room.solved?"result success":"result"}>{result}</p>}</section></>}
 {location==="VELVET"&&<><div className="location-title"><span>ORT 01</span><h2>NACHTCLUB VELVET</h2><p>Letzter bestätigter Aufenthaltsort von Vanessa Kern.</p></div><div className="tabs"><button className={tab==="scene"?"active":""} onClick={()=>setTab("scene")}>AUSSENBEREICH</button><button className={tab==="cctv"?"active":""} onClick={()=>setTab("cctv")}>CCTV</button><button className={tab==="people"?"active":""} onClick={()=>setTab("people")}>PERSONEN</button><button className={tab==="intel"?"active":""} onClick={()=>setTab("intel")}>{me.role==="INSIDER"?"AUSSAGEN":"REGISTER"}</button></div>{tab==="scene"&&<section className="scene-card"><div className="scene-image"><img src="/velvet-exterior.svg"/><button className="hotspot h1" onClick={()=>clue("Hintereingang des VELVET untersucht")}>+</button><button className="hotspot h2" onClick={()=>clue("Leuchtreklame / Haupteingang untersucht")}>+</button></div><div className="scene-copy"><h3>UNTERSUCHT DEN ORT</h3><p>Klickt auf markierte Bereiche. Nicht jeder Punkt ist wichtig, aber manche Beobachtungen werden später relevant.</p></div></section>}{tab==="cctv"&&<Cctv data={caseData} onClue={clue}/>} {tab==="people"&&<div className="people-grid">{(caseData.people||[{name:"Leo Hartmann",detail:"Unternehmer und Stammgast."},{name:"Mila Novak",detail:"Barkeeperin und Freundin von Vanessa."},{name:"Daniel Krüger",detail:"Kriminalbeamter mit ungeklärtem Bezug zum Club."}]).map(p=><article className="person" key={p.name}><div className="avatar">{p.name.split(" ").map(x=>x[0]).join("")}</div><h3>{p.name}</h3><p>{p.detail}</p><button onClick={()=>clue(`Personenakte ${p.name} geprüft`)}>AKTE PRÜFEN</button></article>)}</div>}{tab==="intel"&&<>{me.role==="INSIDER"?<div className="intel-list"><h3>INOFFIZIELLE AUSSAGEN</h3>{caseData.witness?.map((w,i)=><div key={i} onClick={()=>clue(`Aussage ${i+1} geprüft`)}>{w}</div>)}</div>:<div className="intel-list"><h3>FAHRZEUGREGISTER</h3>{caseData.registry?.map(r=><div key={r.plate} onClick={()=>clue(`Registereintrag ${r.plate} geprüft`)}><b>{r.plate}</b><span>{r.owner}</span><span>{r.person}</span></div>)}</div>}</>}</>}
 {location==="HOTEL"&&<div className="locked-preview"><span>NEUER ORT</span><h2>HOTEL // ZIMMER 307</h2><p>Dieser Abschnitt wird als nächstes zur vollwertigen Szene ausgebaut. Für Version 0.3 ist bereits der Übergang freigeschaltet.</p></div>}
 </section><aside className="side-notes"><h3>SPURENLOG</h3>{room.clues.slice(-8).map((c,i)=><div key={i}>✓ {c}</div>)}<h3>KOOP</h3><p>Ihr seht teilweise unterschiedliche Unterlagen. Sprecht über Details, nicht nur über eure Schlussfolgerung.</p></aside></div></main>;

 if(room?.status==="BRIEFING"&&me){const insider=me.role==="INSIDER";return <main className="screen briefing-screen"><div className="noise"/><section className="panel briefing-card"><div className="eyebrow">NIGHTSHIFT // STRENG VERTRAULICH</div><div className="brief-time">02:17</div><h1>FALL #001</h1><h2>DIE VERSCHWUNDENE</h2><div className="meta">RABENSTADT // SAMSTAG // REGEN</div><div className="divider"/><div className="role-card"><span>DEINE ROLLE</span><h3>{insider?"DER INSIDER":"DER ANALYST"}</h3><p>{insider?"Du kommst an Aussagen, Kontakte und Details, die in keiner offiziellen Akte stehen.":"Du arbeitest mit Kameraarchiven, Registern, Zeitlinien und technischen Spuren."}</p></div><div className="incoming"><span>EINGEHENDE NACHRICHT // VIKTOR BRANDT</span><blockquote>„Vanessa Kern. 26. Sie hat mir etwas genommen. Findet sie vor Sonnenaufgang. Keine Polizei.“</blockquote><b>AUFTRAG: 5.000 €</b></div><button className="primary" disabled={me.ready} onClick={ready}>{me.ready?"BEREIT // WARTE AUF PARTNER":"ICH BIN BEREIT"}</button><div className="readyline">{room.players.map(p=><span key={p.id} className={p.ready?"ready":""}>● {p.name}</span>)}</div></section></main>}
 if(room)return <main className="screen"><section className="panel lobby-card"><div className="eyebrow">SICHERE VERBINDUNG // FALLVORBEREITUNG</div><h1 className="logo small">NIGHTSHIFT</h1><div className="room-code-label">EINSATZCODE</div><div className="room-code">{room.code}</div><div className="divider"/><div className="players">{room.players.map(p=><div className="player-row" key={p.id}><span>{p.name}</span><span>{p.host?"HOST":"PARTNER"} · ONLINE</span></div>)}</div>{room.players.length===1?<p className="waiting pulse">Warte auf sichere Verbindung…</p>:me?.host?<button className="primary" onClick={start}>FALL 001 STARTEN</button>:<p className="waiting">Host startet den Fall…</p>}</section></main>;
 return <main className="screen home"><div className="noise"/><section className="panel home-card"><div className="status"><span className={connected?"dot online":"dot"}/>{connected?"NETZWERK BEREIT":"OFFLINE"}</div><div className="eyebrow">A TWO PLAYER CRIME MYSTERY</div><h1 className="logo">NIGHTSHIFT</h1><p className="tagline">Zwei Ermittler. Ein Fall. Keine Abkürzung.</p><label>CODENAME</label><input value={playerName} onChange={e=>setPlayerName(e.target.value)} placeholder="Dein Codename" maxLength={20}/><button className="primary" onClick={create} disabled={!connected||!playerName.trim()}>NEUEN FALL ERÖFFNEN</button><div className="divider"><span>ODER</span></div><label>EINSATZCODE</label><input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} placeholder="XXXXXX" maxLength={6}/><button onClick={join} disabled={!connected||!playerName.trim()||joinCode.length!==6}>PARTNER BEITRETEN</button>{error&&<p className="error">{error}</p>}</section></main>;
}
